parameters:
        mailer_transport: smtp
        mailer_host: 127.0.0.1
        mailer_user: admin@localhost
        mailer_password: null
        secret: ba52e1c44232b0d380ab626ae738cdd2614c8338
        database_path: '%kernel.project_dir%/var/data/data.sqlite'