#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# the "app_lucky_number" route name is not important yet
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"